/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 rover.gltf 
Author: hartwelkisaka (https://sketchfab.com/hartwelkisaka)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mars-rover-44b41a637cc44db1aa9fbff0a1ed63fe
Title: Mars Rover
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/rover.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <mesh geometry={nodes.Object_7.geometry} material={materials.material_0} position={[0.443, -203.552, 316.493]} scale={1.844} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.material_1} position={[0.443, -203.552, 316.493]} scale={1.844} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.material_2} position={[0.443, -203.552, 316.493]} scale={1.844} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.material_3} position={[0.443, -203.552, 316.493]} scale={1.844} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.material_4} position={[0.443, -203.552, 316.493]} scale={1.844} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.material_5} position={[0.443, -203.552, 316.493]} scale={1.844} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.material_6} position={[0.443, -203.552, 316.493]} scale={1.844} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.material_7} position={[0.443, -203.552, 316.493]} scale={1.844} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.material_8} position={[0.443, -203.552, 316.493]} scale={1.844} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.material_9} position={[0.443, -203.552, 316.493]} scale={1.844} />
      </group>
    </group>
  )
}

useGLTF.preload('/rover.gltf')
